#!/bin/bash
#
# wpa2-personal.sh

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
base_dir="$(cd "${script_dir}/.." && pwd)"
source "${base_dir}/src/change_mac.sh"
source "${base_dir}/src/detect_phy.sh"
source "${base_dir}/src/setup_ns.sh"
source "${base_dir}/src/setup_ip.sh"
source "${base_dir}/src/setup_txpower.sh"
source "${base_dir}/src/setup_ap.sh"
source "${base_dir}/src/setup_dhcp_server.sh"
source "${base_dir}/src/setup_sta.sh"
source "${base_dir}/src/gen_traffic.sh"

ap_iface="wlan4"
sta_iface="wlan5"
ap_ns="ap-wpa2-personal"
sta_ns="sta-wpa2-personal"
ip_addr="10.10.10.1/24"
hostapd_conf="${base_dir}/conf/wpa2-personal/hostapd.conf"
dnsmasq_conf="${base_dir}/conf/wpa2-personal/dnsmasq.conf"
wpa_supplicant_conf="${base_dir}/conf/wpa2-personal/wpa_supplicant.conf"
txpower=800

change_mac "${ap_iface}"
change_mac "${sta_iface}"
detect_phy "${ap_iface}"
ap_phy="${phy}"
detect_phy "${sta_iface}"
sta_phy="${phy}"
setup_ns "${ap_ns}" "${ap_phy}"
setup_ns "${sta_ns}" "${sta_phy}"
setup_ip "${ap_ns}" "${ip_addr}" "${ap_iface}"
setup_txpower "${ap_ns}" "${ap_iface}" "${txpower}"
setup_txpower "${sta_ns}" "${sta_iface}" "${txpower}"
setup_ap "${ap_ns}" "${hostapd_conf}"
setup_dhcp_server "${ap_ns}" "${dnsmasq_conf}"
setup_sta "${sta_ns}" "${sta_iface}" "${wpa_supplicant_conf}"
gen_traffic "${ap_ns}" "${sta_ns}" "10.10.10.1"
